baseURL = 'http://example.org/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'vi-VN'
defaultContentLanguage = 'vi'
theme = 'lowkey'
title = 'CodeTrek Nomad'
enableRobotsTXT = true
summaryLength = 15
paginate = 30

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
