baseURL = 'https://codetrek.xyz'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'lowkey'
title = 'CodeTrek Nomad'
enableRobotsTXT = true
summaryLength = 15

[pagination]
  pagerSize = 100

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = false
    noHl = false 
    tabWidth = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
